
"""
db.py - PostgreSQL layer for paycheck-sentinel.

Connection settings come from environment variables (same pattern as REDIS_HOST):
    DB_HOST, DB_PORT (default 5432), DB_NAME (default bailiff),
    DB_USER (default bailiff), DB_PASSWORD (required)

All state that must be shared between instances (batches, transactions,
false-alarm marks) lives here, so any bailiff instance can serve any request.

Developed by Zeljko Tripcevski
"""

import json
import os
import sqlite3
import time
from datetime import datetime, timezone

import psycopg
from psycopg.rows import dict_row


SCHEMA_LOCK_ID = 727001
INIT_RETRIES = 10
INIT_RETRY_DELAY = 2


SCHEMA = """
CREATE TABLE IF NOT EXISTS batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL,
    created_at TEXT NOT NULL,
    file_names TEXT NOT NULL,
    columns_json TEXT NOT NULL,
    row_count INTEGER NOT NULL,
    own_account TEXT,

    mode TEXT DEFAULT 'generic',

    paid_col TEXT,
    returned_col TEXT,
    id_col TEXT,
    debtor_col TEXT,
    date_col TEXT,
    tolerance DOUBLE PRECISION DEFAULT 0,
    outlier_multiplier DOUBLE PRECISION DEFAULT 5,
    check_full INTEGER DEFAULT 1,
    check_partial INTEGER DEFAULT 1,
    check_dupid INTEGER DEFAULT 0,
    check_duppay INTEGER DEFAULT 0,
    check_outlier INTEGER DEFAULT 0,

    amount_col TEXT,
    benefit_col TEXT,
    ref_col TEXT,
    debit_value TEXT DEFAULT 'debit',
    credit_value TEXT DEFAULT 'credit',
    max_days_gap DOUBLE PRECISION DEFAULT 30,
    require_refnumber INTEGER DEFAULT 0,

    from_col TEXT,
    to_col TEXT,
    account_from TEXT,
    account_to TEXT,

    analyzed INTEGER DEFAULT 0,
    flagged_count INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
    source_file TEXT,
    row_index INTEGER NOT NULL,
    raw_json TEXT NOT NULL,
    paid_amount DOUBLE PRECISION,
    returned_amount DOUBLE PRECISION,
    flags_json TEXT DEFAULT '[]',
    is_false_alarm INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_transactions_batch
ON transactions(batch_id);
"""


def _sqlite_enabled():
    return os.environ.get("PAYCHECK_SENTINEL_DB", "").lower() in {
        "sqlite",
        "sqlite3",
        "local",
    }


class SQLiteCursor:
    """Compatibility wrapper for SQLite cursors."""

    def __init__(self, cursor):
        self._cursor = cursor

    def execute(self, sql, params=()):
        self._cursor.execute(sql.replace("%s", "?"), params)
        return self

    def executemany(self, sql, params):
        self._cursor.executemany(sql.replace("%s", "?"), params)
        return self

    def __enter__(self):
        # sqlite3.Cursor does not implement the context manager protocol.
        return self

    def __exit__(self, exc_type, exc, tb):
        # Close the cursor without committing or rolling back the connection.
        self._cursor.close()
        return False

    def close(self):
        self._cursor.close()

    def __getattr__(self, name):
        return getattr(self._cursor, name)


class SQLiteConnection:
    """Compatibility wrapper for SQLite connections."""

    def __init__(self, connection):
        self._connection = connection

    def execute(self, sql, params=()):
        return self._connection.execute(sql.replace("%s", "?"), params)

    def executemany(self, sql, params):
        return self._connection.executemany(sql.replace("%s", "?"), params)

    def cursor(self):
        return SQLiteCursor(self._connection.cursor())

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()

    def executescript(self, sql):
        return self._connection.executescript(sql)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        try:
            if exc_type is None:
                self.commit()
            else:
                self.rollback()
        finally:
            self.close()

        return False

    def __getattr__(self, name):
        return getattr(self._connection, name)


def get_db():
    """Open a PostgreSQL or local SQLite connection."""

    if _sqlite_enabled():
        default_path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "instance",
            "bailiff.sqlite3",
        )

        path = os.environ.get("PAYCHECK_SENTINEL_DB_PATH", default_path)
        directory = os.path.dirname(os.path.abspath(path))
        os.makedirs(directory, exist_ok=True)

        connection = sqlite3.connect(path, timeout=5)
        connection.row_factory = sqlite3.Row
        connection.execute("PRAGMA foreign_keys = ON")

        return SQLiteConnection(connection)

    return psycopg.connect(
        host=os.environ.get("DB_HOST", "localhost"),
        port=int(os.environ.get("DB_PORT", "5432")),
        dbname=os.environ.get("DB_NAME", "bailiff"),
        user=os.environ.get("DB_USER", "bailiff"),
        password=os.environ["DB_PASSWORD"],
        row_factory=dict_row,
        connect_timeout=5,
    )


def init_db():
    """Create the schema for the selected database backend."""

    if _sqlite_enabled():
        sqlite_schema = SCHEMA.replace(
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "INTEGER PRIMARY KEY AUTOINCREMENT",
        )

        with get_db() as conn:
            conn.executescript(sqlite_schema)

        return

    for attempt in range(1, INIT_RETRIES + 1):
        try:
            with get_db() as conn:
                conn.execute(
                    "SELECT pg_advisory_xact_lock(%s)",
                    (SCHEMA_LOCK_ID,),
                )
                conn.execute(SCHEMA)

            return

        except psycopg.OperationalError:
            if attempt == INIT_RETRIES:
                raise

            time.sleep(INIT_RETRY_DELAY)


def now_iso():
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def create_batch(conn, label, file_names, columns, rows, own_account=None):
    batch_id = conn.execute(
        """
        INSERT INTO batches (
            label, created_at, file_names, columns_json,
            row_count, own_account
        )
        VALUES (%s, %s, %s, %s, %s, %s)
        RETURNING id
        """,
        (
            label,
            now_iso(),
            json.dumps(file_names),
            json.dumps(columns),
            len(rows),
            own_account,
        ),
    ).fetchone()["id"]

    with conn.cursor() as cur:
        cur.executemany(
            """
            INSERT INTO transactions (
                batch_id, source_file, row_index, raw_json
            )
            VALUES (%s, %s, %s, %s)
            """,
            [
                (
                    batch_id,
                    row.get("__source_file", ""),
                    index,
                    json.dumps(row, ensure_ascii=False),
                )
                for index, row in enumerate(rows)
            ],
        )

    conn.commit()
    return batch_id


def list_batches(conn):
    rows = conn.execute(
        "SELECT * FROM batches ORDER BY id DESC"
    ).fetchall()

    return [dict(row) for row in rows]


def get_batch(conn, batch_id):
    row = conn.execute(
        "SELECT * FROM batches WHERE id = %s",
        (batch_id,),
    ).fetchone()

    return dict(row) if row else None


def delete_batch(conn, batch_id):
    conn.execute(
        "DELETE FROM batches WHERE id = %s",
        (batch_id,),
    )
    conn.commit()


def get_transactions(conn, batch_id):
    rows = conn.execute(
        """
        SELECT *
        FROM transactions
        WHERE batch_id = %s
        ORDER BY row_index
        """,
        (batch_id,),
    ).fetchall()

    result = []

    for row in rows:
        raw = json.loads(row["raw_json"])

        result.append(
            {
                "idx": row["row_index"],
                "raw": raw,
                "paid_amount": row["paid_amount"],
                "returned_amount": row["returned_amount"],
                "flags": json.loads(row["flags_json"]),
                "is_false_alarm": bool(row["is_false_alarm"]),
            }
        )

    return result


def set_false_alarm(conn, batch_id, row_index, value):
    conn.execute(
        """
        UPDATE transactions
        SET is_false_alarm = %s
        WHERE batch_id = %s AND row_index = %s
        """,
        (int(bool(value)), batch_id, row_index),
    )
    conn.commit()


def save_bank_analysis(conn, batch_id, mapping, options, analyzed_txns):
    conn.execute(
        """
        UPDATE batches SET
            mode = 'bank_statement',
            amount_col = %s,
            benefit_col = %s,
            ref_col = %s,
            date_col = %s,
            debit_value = %s,
            credit_value = %s,
            max_days_gap = %s,
            require_refnumber = %s,
            analyzed = 1,
            flagged_count = %s
        WHERE id = %s
        """,
        (
            mapping.get("amount_col"),
            mapping.get("benefit_col"),
            mapping.get("ref_col"),
            mapping.get("date_col"),
            options.get("debit_value", "debit"),
            options.get("credit_value", "credit"),
            options.get("max_days_gap", 30),
            int(bool(options.get("require_refnumber"))),
            sum(1 for txn in analyzed_txns if txn["flags"]),
            batch_id,
        ),
    )

    with conn.cursor() as cur:
        cur.executemany(
            """
            UPDATE transactions
            SET paid_amount = %s, flags_json = %s
            WHERE batch_id = %s AND row_index = %s
            """,
            [
                (
                    txn["amount"],
                    json.dumps(txn["flags"], ensure_ascii=False),
                    batch_id,
                    txn["idx"],
                )
                for txn in analyzed_txns
            ],
        )

    conn.commit()


def save_transfer_analysis(conn, batch_id, mapping, options, analyzed_txns):
    conn.execute(
        """
        UPDATE batches SET
            mode = 'transfer',
            from_col = %s,
            to_col = %s,
            amount_col = %s,
            date_col = %s,
            account_from = %s,
            account_to = %s,
            analyzed = 1,
            flagged_count = %s
        WHERE id = %s
        """,
        (
            mapping.get("from_col"),
            mapping.get("to_col"),
            mapping.get("amount_col"),
            mapping.get("date_col"),
            options.get("account_from", ""),
            options.get("account_to", ""),
            sum(1 for txn in analyzed_txns if txn["flags"]),
            batch_id,
        ),
    )

    with conn.cursor() as cur:
        cur.executemany(
            """
            UPDATE transactions
            SET paid_amount = %s, flags_json = %s
            WHERE batch_id = %s AND row_index = %s
            """,
            [
                (
                    txn["paid_amount"],
                    json.dumps(txn["flags"], ensure_ascii=False),
                    batch_id,
                    txn["idx"],
                )
                for txn in analyzed_txns
            ],
        )

    conn.commit()


def save_analysis(conn, batch_id, mapping, options, analyzed_txns):
    conn.execute(
        """
        UPDATE batches SET
            paid_col = %s,
            returned_col = %s,
            id_col = %s,
            debtor_col = %s,
            date_col = %s,
            tolerance = %s,
            outlier_multiplier = %s,
            check_full = %s,
            check_partial = %s,
            check_dupid = %s,
            check_duppay = %s,
            check_outlier = %s,
            analyzed = 1,
            flagged_count = %s
        WHERE id = %s
        """,
        (
            mapping.get("paid_col"),
            mapping.get("returned_col"),
            mapping.get("id_col"),
            mapping.get("debtor_col"),
            mapping.get("date_col"),
            options.get("tolerance", 0),
            options.get("outlier_multiplier", 5),
            int(bool(options.get("check_full"))),
            int(bool(options.get("check_partial"))),
            int(bool(options.get("check_dupid"))),
            int(bool(options.get("check_duppay"))),
            int(bool(options.get("check_outlier"))),
            sum(1 for txn in analyzed_txns if txn["flags"]),
            batch_id,
        ),
    )

    with conn.cursor() as cur:
        cur.executemany(
            """
            UPDATE transactions
            SET
                paid_amount = %s,
                returned_amount = %s,
                flags_json = %s
            WHERE batch_id = %s AND row_index = %s
            """,
            [
                (
                    txn["paid_amount"],
                    txn["returned_amount"],
                    json.dumps(txn["flags"], ensure_ascii=False),
                    batch_id,
                    txn["idx"],
                )
                for txn in analyzed_txns
            ],
        )

    conn.commit()