"""
db.py - PostgreSQL layer for paycheck-sentinel.

Connection settings come from environment variables (same pattern as REDIS_HOST):
    DB_HOST, DB_PORT (default 5432), DB_NAME (default bailiff),
    DB_USER (default bailiff), DB_PASSWORD (required)

All state that must be shared between instances (batches, transactions,
false-alarm marks) lives here, so any bailiff instance can serve any request.

Developed by Zeljko Tripcevski
"""

import json
import os
import time
from datetime import datetime, timezone

import psycopg
from psycopg.rows import dict_row

# Arbitrary constant: all instances use the same number, so only one of them
# creates the schema at a time when several containers start simultaneously.
SCHEMA_LOCK_ID = 727001
INIT_RETRIES = 10
INIT_RETRY_DELAY = 2  # seconds

SCHEMA = """
CREATE TABLE IF NOT EXISTS batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL,
    created_at TEXT NOT NULL,
    file_names TEXT NOT NULL,       -- JSON list of uploaded file names
    columns_json TEXT NOT NULL,     -- JSON list of detected columns
    row_count INTEGER NOT NULL,
    own_account TEXT,               -- account owner of the statement (iBank format), if detected

    mode TEXT DEFAULT 'generic',    -- 'generic' (paid/returned columns) or 'bank_statement' (debit/credit)

    paid_col TEXT,
    returned_col TEXT,
    id_col TEXT,
    debtor_col TEXT,
    date_col TEXT,
    tolerance DOUBLE PRECISION DEFAULT 0,
    outlier_multiplier DOUBLE PRECISION DEFAULT 5,
    check_full INTEGER DEFAULT 1,
    check_partial INTEGER DEFAULT 1,
    check_dupid INTEGER DEFAULT 0,
    check_duppay INTEGER DEFAULT 0,
    check_outlier INTEGER DEFAULT 0,

    amount_col TEXT,
    benefit_col TEXT,
    ref_col TEXT,
    debit_value TEXT DEFAULT 'debit',
    credit_value TEXT DEFAULT 'credit',
    max_days_gap DOUBLE PRECISION DEFAULT 30,
    require_refnumber INTEGER DEFAULT 0,

    from_col TEXT,
    to_col TEXT,
    account_from TEXT,
    account_to TEXT,

    analyzed INTEGER DEFAULT 0,
    flagged_count INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
    source_file TEXT,
    row_index INTEGER NOT NULL,
    raw_json TEXT NOT NULL,
    paid_amount DOUBLE PRECISION,
    returned_amount DOUBLE PRECISION,
    flags_json TEXT DEFAULT '[]',
    is_false_alarm INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_transactions_batch ON transactions(batch_id);
"""


def get_db():
    """Open a new connection. Rows come back as dicts (row["name"] and dict(row) both work)."""
    return psycopg.connect(
        host=os.environ.get("DB_HOST", "localhost"),
        port=int(os.environ.get("DB_PORT", "5432")),
        dbname=os.environ.get("DB_NAME", "bailiff"),
        user=os.environ.get("DB_USER", "bailiff"),
        password=os.environ["DB_PASSWORD"],
        row_factory=dict_row,
        connect_timeout=5,
    )


def init_db():
    """Create the schema if it does not exist.

    Retries while the database is still starting (containers may boot in any
    order) and takes an advisory lock so that bailiff-1/2/3 starting at the
    same time do not race on CREATE TABLE.
    """
    for attempt in range(1, INIT_RETRIES + 1):
        try:
            with get_db() as conn:  # commits on success, closes at the end
                conn.execute("SELECT pg_advisory_xact_lock(%s)", (SCHEMA_LOCK_ID,))
                conn.execute(SCHEMA)
            return
        except psycopg.OperationalError:
            if attempt == INIT_RETRIES:
                raise
            time.sleep(INIT_RETRY_DELAY)


def now_iso():
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def create_batch(conn, label, file_names, columns, rows, own_account=None):
    batch_id = conn.execute(
        """INSERT INTO batches (label, created_at, file_names, columns_json, row_count, own_account)
           VALUES (%s, %s, %s, %s, %s, %s)
           RETURNING id""",
        (label, now_iso(), json.dumps(file_names), json.dumps(columns), len(rows), own_account),
    ).fetchone()["id"]

    with conn.cursor() as cur:
        cur.executemany(
            """INSERT INTO transactions (batch_id, source_file, row_index, raw_json)
               VALUES (%s, %s, %s, %s)""",
            [
                (batch_id, r.get("__source_file", ""), i, json.dumps(r, ensure_ascii=False))
                for i, r in enumerate(rows)
            ],
        )
    conn.commit()
    return batch_id


def list_batches(conn):
    rows = conn.execute("SELECT * FROM batches ORDER BY id DESC").fetchall()
    return [dict(r) for r in rows]


def get_batch(conn, batch_id):
    row = conn.execute("SELECT * FROM batches WHERE id = %s", (batch_id,)).fetchone()
    return dict(row) if row else None


def delete_batch(conn, batch_id):
    conn.execute("DELETE FROM batches WHERE id = %s", (batch_id,))
    conn.commit()


def get_transactions(conn, batch_id):
    rows = conn.execute(
        "SELECT * FROM transactions WHERE batch_id = %s ORDER BY row_index", (batch_id,)
    ).fetchall()
    result = []
    for r in rows:
        raw = json.loads(r["raw_json"])
        result.append({
            "idx": r["row_index"],
            "raw": raw,
            "paid_amount": r["paid_amount"],
            "returned_amount": r["returned_amount"],
            "flags": json.loads(r["flags_json"]),
            "is_false_alarm": bool(r["is_false_alarm"]),
        })
    return result


def set_false_alarm(conn, batch_id, row_index, value):
    conn.execute(
        "UPDATE transactions SET is_false_alarm = %s WHERE batch_id = %s AND row_index = %s",
        (int(bool(value)), batch_id, row_index),
    )
    conn.commit()


def save_bank_analysis(conn, batch_id, mapping, options, analyzed_txns):
    conn.execute(
        """UPDATE batches SET
             mode = 'bank_statement',
             amount_col = %s, benefit_col = %s, ref_col = %s, date_col = %s,
             debit_value = %s, credit_value = %s, max_days_gap = %s, require_refnumber = %s,
             analyzed = 1, flagged_count = %s
           WHERE id = %s""",
        (
            mapping.get("amount_col"), mapping.get("benefit_col"),
            mapping.get("ref_col"), mapping.get("date_col"),
            options.get("debit_value", "debit"), options.get("credit_value", "credit"),
            options.get("max_days_gap", 30), int(bool(options.get("require_refnumber"))),
            sum(1 for t in analyzed_txns if t["flags"]),
            batch_id,
        ),
    )

    # One executemany instead of one round trip per row.
    with conn.cursor() as cur:
        cur.executemany(
            """UPDATE transactions SET paid_amount = %s, flags_json = %s
               WHERE batch_id = %s AND row_index = %s""",
            [
                (t["amount"], json.dumps(t["flags"], ensure_ascii=False), batch_id, t["idx"])
                for t in analyzed_txns
            ],
        )
    conn.commit()


def save_transfer_analysis(conn, batch_id, mapping, options, analyzed_txns):
    conn.execute(
        """UPDATE batches SET
             mode = 'transfer',
             from_col = %s, to_col = %s, amount_col = %s, date_col = %s,
             account_from = %s, account_to = %s,
             analyzed = 1, flagged_count = %s
           WHERE id = %s""",
        (
            mapping.get("from_col"), mapping.get("to_col"),
            mapping.get("amount_col"), mapping.get("date_col"),
            options.get("account_from", ""), options.get("account_to", ""),
            sum(1 for t in analyzed_txns if t["flags"]),
            batch_id,
        ),
    )

    with conn.cursor() as cur:
        cur.executemany(
            """UPDATE transactions SET paid_amount = %s, flags_json = %s
               WHERE batch_id = %s AND row_index = %s""",
            [
                (t["paid_amount"], json.dumps(t["flags"], ensure_ascii=False), batch_id, t["idx"])
                for t in analyzed_txns
            ],
        )
    conn.commit()


def save_analysis(conn, batch_id, mapping, options, analyzed_txns):
    conn.execute(
        """UPDATE batches SET
             paid_col = %s, returned_col = %s, id_col = %s, debtor_col = %s, date_col = %s,
             tolerance = %s, outlier_multiplier = %s,
             check_full = %s, check_partial = %s, check_dupid = %s, check_duppay = %s,
             check_outlier = %s,
             analyzed = 1, flagged_count = %s
           WHERE id = %s""",
        (
            mapping.get("paid_col"), mapping.get("returned_col"), mapping.get("id_col"),
            mapping.get("debtor_col"), mapping.get("date_col"),
            options.get("tolerance", 0), options.get("outlier_multiplier", 5),
            int(bool(options.get("check_full"))),
            int(bool(options.get("check_partial"))),
            int(bool(options.get("check_dupid"))),
            int(bool(options.get("check_duppay"))),
            int(bool(options.get("check_outlier"))),
            sum(1 for t in analyzed_txns if t["flags"]),
            batch_id,
        ),
    )

    with conn.cursor() as cur:
        cur.executemany(
            """UPDATE transactions SET paid_amount = %s, returned_amount = %s, flags_json = %s
               WHERE batch_id = %s AND row_index = %s""",
            [
                (
                    t["paid_amount"], t["returned_amount"],
                    json.dumps(t["flags"], ensure_ascii=False),
                    batch_id, t["idx"],
                )
                for t in analyzed_txns
            ],
        )
    conn.commit()
